#!/bin/bash

set -e
. "$BACKUP_DRIVER_DIR/rdiff-backup.conf"
set +e

: ${AUTO_PRUNE:=false}
: ${AUTO_PRUNE_DELAY:=1W}

get_destdir(){
    destdir="${1#/}"; destdir="${destdir%/}"; destdir="${destdir//\//-}"
}

act="$1"
shift
case "$act" in
    init)
        subact="$1"
        shift
        set -e
        ( set -x
          rdiff-backup "${FLAGS[@]}" "$@" --test-server "$DESTINATION"
        )
    ;;
    backup)
        dir="$1"
        get_destdir "$1"
        dirflags=()
        if ! [[ -d $dir ]]; then
            dirflags=(--include "$(readlink -f "${dir%/*}")/${dir##*/}" --exclude '**')
            dir="${dir%/*}/"
        fi
        shift
        set -e
        ( set -x
          rdiff-backup "${FLAGS[@]}" "$@" "${dirflags[@]}" "$(readlink -f "$dir")" "$DESTINATION/$destdir"
        )
        set +e
        if $AUTO_PRUNE; then
        ( set -x
          rdiff-backup "${FLAGS[@]}" --remove-older-than "$AUTO_PRUNE_DELAY" "$DESTINATION/$destdir"
        )
        fi
    ;;
    list)
        dir="$1"
        get_destdir "$1"
        shift
        set -e
        ( set -x
          rdiff-backup --list-increments "${FLAGS[@]}" "$@" "$DESTINATION/$destdir"
        )
    ;;
    restore)
        dir="$1"
        get_destdir "$1"
        shift
        set -e
        ( set -x
          rdiff-backup --restore-as-of now "${FLAGS[@]}" "$@" "$DESTINATION/$destdir" "$(readlink -f "$dir")"
        )
    ;;
    commit)
        subact="$1"
        shift
    ;;
    *)
        echo "Unimplemented $act"
    ;;
esac